COLUMN_TYPES = {
    "download": "REAL NOT NULL",
    "upload": "REAL NOT NULL",
    "ping": "REAL NOT NULL",
    "server_url": "TEXT",
    "server_lat": "TEXT",
    "server_lon": "TEXT",
    "server_name": "TEXT",
    "server_country": "TEXT",
    "server_cc": "TEXT",
    "server_sponsor": "TEXT",
    "server_id": "TEXT",
    "server_host": "TEXT",
    "server_d": "REAL",
    "server_latency": "REAL",
    "timestamp": "NUM NOT NULL",
    "bytes_sent": "NUM",
    "bytes_received": "NUM",
    "share": "TEXT",
    "client_ip": "TEXT",
    "client_lat": "TEXT",
    "client_lon": "TEXT",
    "client_isp": "TEXT",
    "client_isprating": "TEXT",
    "client_rating": "TEXT",
    "client_ispdlavg": "TEXT",
    "client_ispulavg": "TEXT",
    "client_loggedin": "TEXT",
    "client_country": "TEXT",
}
